name: CI Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Verify Java version
        run: java -version

      - name: Install Cloc
        run: sudo apt-get install -y cloc

      - name: Count lines of code with Cloc
        run: |
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Upload Cloc report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloc-report
          path: cloc-report.txt

      - name: Set up SonarCloud scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$(pwd)/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=nazar-vi_pythonproject \
            -Dsonar.organization=nazar-vi \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
